# Generated by Django 3.0.2 on 2020-02-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_fname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_lname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
