# Generated by Django 3.0.2 on 2020-02-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20200220_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_mobile',
            field=models.IntegerField(),
        ),
    ]
